topic: "online business ideas UK"
jurisdiction: UK
currency: GBP
delivery: online-first
constraints: [no-dropshipping, no-physical-retail, uk-based]
source: aiden.research
created: 2025-08-24T18:26:56.868Z
